/*
package database;

import java.sql.*;
import org.centrale.objet.WoE.*;

/**
 * Handles saving of all Creature instances (Personnage and Monstre subclasses)
 * with the real attributes from your Java classes.
 *
public class CreatureDB {

    /**
     * Saves a Creature (any subclass) into the database.
     *
     * @param creature  The Creature instance (Guerrier, Archer, Paysan, Loup, Lapin, etc.)
     * @param idRace    Race ID (Humain, Loup, Lapin…)
     * @param idElement Element ID (position)
     * @param idMetier  Metier ID if humanoid (Guerrier, Archer, Paysan), null otherwise
     * @return idCreature generated by the DB
     *
    public static int saveCreature(Creature creature,
                                   int idRace,
                                   int idElement,
                                   Integer idMetier) throws SQLException {

        int idCreature = insertBaseCreature(creature, idRace, idElement);

        if (creature instanceof Personnage p && idMetier != null) {
            insertHumanoidInfo(idCreature, p, idMetier);
        }

        saveAttributes(idCreature, idMetier, creature);
        return idCreature;
    }

    /** Inserts into Creature table (base info + position). *
    private static int insertBaseCreature(Creature creature, int idRace, int idElement) throws SQLException {
        String sql = """
            INSERT INTO Creature (nom, idRace, idElement)
            VALUES (?, ?, ?)
            RETURNING idCreature;
        """;
        int id = -1;
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            // Only humanoids (Personnage) have a name
            if (creature instanceof Personnage p)
                ps.setString(1, p.getNom());
            else
                ps.setNull(1, Types.VARCHAR);

            ps.setInt(2, idRace);
            ps.setInt(3, idElement);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) id = rs.getInt("idCreature");
        }
        return id;
    }

    /** Inserts humanoid info into CreatureHumaine. *
    private static void insertHumanoidInfo(int idCreature, Personnage p, int idMetier) throws SQLException {
        String sql = "INSERT INTO CreatureHumaine (idCreaHumaine, nom, idMetier) VALUES (?, ?, ?)";
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, idCreature);
            ps.setString(2, p.getNom());
            ps.setInt(3, idMetier);
            ps.executeUpdate();
        }
    }

    /**
     * Saves all real attributes of the Creature into CaracValues.
     * Attributes (from your code): ptVie, degAtt, ptPar, pageAtt, pagePar, distAttMax, nbFleches (Archer).
     *
    private static void saveAttributes(int idCreature, Integer idMetier, Creature c) throws SQLException {
        String sql = """
            INSERT INTO CaracValues (idCarac, idMetier, idCreaHumaine, caracValue)
            VALUES (?, ?, ?, ?);
        """;

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            // ---- Base Creature attributes ----
            insertAttr(ps, 1, idMetier, idCreature, c.getPtVie());
            insertAttr(ps, 2, idMetier, idCreature, c.getDegAtt());
            insertAttr(ps, 3, idMetier, idCreature, c.getPtPar());
            insertAttr(ps, 4, idMetier, idCreature, c.getPageAtt());
            insertAttr(ps, 5, idMetier, idCreature, c.getPagePar());

            // ---- Personnage attributes ----
            if (c instanceof Personnage p) {
                insertAttr(ps, 6, idMetier, idCreature, p.getDistAttMax());
            }

            // ---- Archer-specific attribute ----
            if (c instanceof Archer a) {
                insertAttr(ps, 7, idMetier, idCreature, a.getNbFleches());
            }
        }
    }

    /** Helper to insert one attribute row in CaracValues. *
    private static void insertAttr(PreparedStatement ps,
                                   int idCarac,
                                   Integer idMetier,
                                   int idCreature,
                                   double value) throws SQLException {
        ps.setInt(1, idCarac);
        if (idMetier != null) ps.setInt(2, idMetier);
        else ps.setNull(2, Types.INTEGER);
        ps.setInt(3, idCreature);
        ps.setDouble(4, value);
        ps.addBatch();
        ps.executeBatch();
    }

    /** Lists all creatures for debug. *
    public static void listCreatures() throws SQLException {
        String sql = """
            SELECT c.idCreature, c.nom, r.libelleRace, e.posX, e.posY
            FROM Creature c
            JOIN Race r ON c.idRace = r.idRace
            JOIN Element e ON c.idElement = e.idElement
            ORDER BY c.idCreature;
        """;
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            System.out.println("=== Liste des Créatures ===");
            while (rs.next()) {
                System.out.printf("ID:%d | Nom:%s | Race:%s | Pos:(%d,%d)%n",
                        rs.getInt("idCreature"),
                        rs.getString("nom"),
                        rs.getString("libelleRace"),
                        rs.getInt("posX"),
                        rs.getInt("posY"));
            }
        }
    }
}
*/
