package database;

import java.sql.*;
import org.centrale.objet.WoE.*;

/**
 * Handles saving of all in-game objects (Épée, PotionSoin, Nourriture, etc.)
 * with every real attribute into the database.
 */
public class ObjetDB {

    /**
     * Saves an Objet (any subclass) into the database.
     *
     * @param objet     Java object instance
     * @param idTypeObj ID from TypeObjet (Epee, PotionSoin, etc.)
     * @param idElement Element ID where it’s located
     * @return idObjet generated by the DB
     */
    public static int saveObjet(Objet objet, int idTypeObj, int idElement) throws SQLException {
        int idObjet = insertBaseObjet(objet, idTypeObj, idElement);
        saveAllAttributes(idObjet, idTypeObj, objet);
        return idObjet;
    }

    /** Inserts the base object record (nom, type, position). */
    private static int insertBaseObjet(Objet objet, int idTypeObj, int idElement) throws SQLException {
        String sql = """
            INSERT INTO Objet (nomObjet, idTypeObjet, idElement)
            VALUES (?, ?, ?)
            RETURNING idObjet;
        """;

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            if (objet.getNom() != null)
                ps.setString(1, objet.getNom());
            else
                ps.setNull(1, Types.VARCHAR);

            ps.setInt(2, idTypeObj);
            ps.setInt(3, idElement);

            ResultSet rs = ps.executeQuery();
            if (rs.next())
                return rs.getInt("idObjet");
        }
        throw new SQLException("Failed to insert Objet");
    }

    /**
     * Saves *all* attributes of an object into Effet.
     * Uses CaracObjet rows already defined for each TypeObjet.
     */
    private static void saveAllAttributes(int idObjet, int idTypeObj, Objet objet) throws SQLException {
        String sqlCarac = """
                        SELECT idCaracObjet, libelleCarac
                        FROM CaracObjet
                        WHERE idTypeObjet = ? 
                           OR libelleCarac = 'dureeEffet'
                    """;
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sqlCarac)) {

            ps.setInt(1, idTypeObj);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int idCaracObjet = rs.getInt("idCaracObjet");
                String caracName = rs.getString("libelleCarac");

                double value = extractValueForAttribute(objet, caracName);

                insertEffet(conn, idObjet, idCaracObjet, value);
            }
        }
    }

    /** Inserts one attribute/value pair into Effet table. */
    private static void insertEffet(Connection conn, int idObjet, int idCaracObjet, double valeur) throws SQLException {
        String sql = "INSERT INTO Effet (idObjet, idCaracObjet, effet) VALUES (?, ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, idObjet);
            ps.setInt(2, idCaracObjet);
            ps.setDouble(3, valeur);
            ps.executeUpdate();
        }
    }

    /** Returns the correct value for the given attribute name from the object instance. */
    private static double extractValueForAttribute(Objet objet, String caracName) {
        // Base attributes are handled per subclass:
        switch (caracName.toLowerCase()) {
            // ⚔Épée
            case "bonusatt":
                if (objet instanceof Epee e) return e.getBonusAtt();
                break;

            // Potion de soin
            case "ptvierendus":
                if (objet instanceof PotionSoin p) return p.getSoin();
                break;

            // Nourriture / FeuilleEpinart / ChampignonPourri share dureeEffet
            case "dureeEffet":
            case "dureeeffet":
                if (objet instanceof Nourriture n) return n.getDureeEffet();
                break;

            // Feuille d’épinard
            case "bonusdegatt":
                if (objet instanceof FeuilleEpinart f) return f.getBonusDegAtt();
                break;

            // Champignon pourri
            case "malusdefense":
                if (objet instanceof ChampignonPourri c) return c.getMalusDefense();
                break;

            // ☠️ Nuage toxique
            case "degatt":
            case "degats":
                if (objet instanceof NuageToxique n) return n.getDegAtt();
                break;
            case "distattmax":
                if (objet instanceof NuageToxique n) return n.getDistAttMax();
                break;
        }
        return 0.0;
    }

    /** Simple debug listing of all objects. */
    public static void listObjets() throws SQLException {
        String sql = """
            SELECT o.idObjet, o.nomObjet, t.libelleObjet, e.posX, e.posY
            FROM Objet o
            JOIN TypeObjet t ON o.idTypeObjet = t.idTypeObjet
            JOIN Element e ON o.idElement = e.idElement
            ORDER BY o.idObjet;
        """;

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            System.out.println("=== Liste des Objets ===");
            while (rs.next()) {
                System.out.printf("ID:%d | Nom:%s | Type:%s | Pos:(%d,%d)%n",
                        rs.getInt("idObjet"),
                        rs.getString("nomObjet"),
                        rs.getString("libelleObjet"),
                        rs.getInt("posX"),
                        rs.getInt("posY"));
            }
        }
    }
}
